apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels: 
    app: va
    type: db-redis
  
spec:
  containers:
    - name: redis-container
      image: redis
      ports:
        - containerPort: 6379
