apiVersion: v1 
kind: Pod
metadata: 
  name: result-pod
  labels:
    app: va 
    type: FE-result
spec:
  containers:
    - name: result-continer
      image: kodekloud/examplevotingapp_result:v1
      ports:
        - containerPort: 80
  