apiVersion: v1 
kind: Service
metadata: 
  name: vote-page-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
  selector:
    app: va 
    type: FE-vote