apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deplo
  labels:
      app: va
      type: db-redis
spec:
  selector:
    matchLabels:
      type: db-redis
    
  template:
    metadata:
      name: redis-pod
      labels: 
        app: va
        type: db-redis
      
    spec:
      containers:
        - name: redis-container
          image: redis
          ports:
            - containerPort: 6379
  replicas: 1
